# Bot Configuration - Local Environment
API_ID = 27112006
API_HASH = "0d1019d7ca92aef12571c82cd163d2bd"
BOT_TOKEN = "8131426614:AAG8htCzWpU7AZGIZ-nU64tReKNXr3pka4U"

# Language Dictionaries
LANGUAGES = {
    "en": {
        "welcome": "Welcome! Please select an option:",
        "login": "🔐 Login",
        "language": "🌐 Language",
        "back": "⬅️ Back",
        "english": "🇺🇸 English",
        "vietnamese": "🇻🇳 Vietnamese",
        "login_prompt": "To activate your username, contact the admin @admin\nOr send your info like this: `username&password`",
        "contact_admin": "Contact admin: /admin_username",
        "login_success": "✅ Login successful! Welcome back.",
        "login_failed": "❌ Invalid credentials. Please try again.",
        "session_expired": "⚠️ Your session has expired. Please login again.",
        "home": "🏠 Home",
        "groups": "📋 Groups",
        "settings": "⚙️ Settings",
        "start": "▶️ Start",
        "stop": "⏹️ Stop",
        "logout": "🚪 Logout",
        "done": "✅ Done",
        "select": "✅ Select",
        "group_selected": "✅ Selected",
        "group_description": "Group Description",
        "admin_panel": "🔧 Admin Panel",
        "group_list": "📋 Group List",
        "add_username": "➕ Add Username",
        "delete_username": "➖ Delete Username",
        "search_usernames": "🔍 Search Usernames",
        "online_list": "🟢 Online List",
        "added_list": "📝 Added List",
        "remove": "🗑️ Remove",
        "add_admin": "➕ Add Admin",
        "remove_admin": "➖ Remove Admin",
        "added_admins": "👥 Added Admins",
        "admin_add_prompt": "Send the new admin ID to add:",
        "admin_remove_prompt": "Send the admin ID to remove:",
        "admin_added": "✅ Admin added successfully!",
        "admin_removed": "✅ Admin removed successfully!",
        "user_info": "User Information",
        "username": "Username",
        "status": "Status",
        "online": "🟢 Online",
        "offline": "🔴 Offline",
        "no_groups": "No groups available",
        "no_users": "No users available",
        "no_admins": "No admins available",
        "group_added": "✅ Group added successfully!",
        "group_removed": "✅ Group removed successfully!",
        "group_updated": "✅ Group updated successfully!",
        "edit": "✏️ Edit",
        "username_added": "✅ Username added successfully!",
        "username_removed": "✅ Username removed successfully!",
        "invalid_format": "❌ Invalid format. Please use: username&password",
        "already_logged_in": "You are already logged in!",
        "not_logged_in": "Please login first!",
        "not_admin": "❌ Access denied. Admin only.",
        "session_days": "Session valid for 3 days",
        "coinvid_login_failed": "❌ Coinvid login failed. Please check your credentials.",
        "trading_started": "✅ Trading started! Ready to receive signals.",
        "trading_stopped": "🛑 Trading stopped!",
        "group_not_selected": "❌ Please select a group first!",
        "credentials_missing": "❌ Please login to Coinvid first!",
        "signal_received": "🎯 Signal received and executed!",
        "trade_success": "✅ Trade executed successfully!",
        "trade_failed": "❌ Trade execution failed!",
        "balance_updated": "💰 Balance updated!",
        "cmd_user_only": "❌ This command can only be used by users, not channels or anonymous admins.",
        "login_btn": "🔐 Login",
        "language_btn": "🌐 Language",
        "groups_btn": "👥 Groups",
        "settings_btn": "⚙️ Settings",
        "start_btn": "▶️ Start",
        "stop_btn": "⏹️ Stop",
        "target_btn": "🎯 Target",
        "capital_mgmt_btn": "💼 Capital management",
        "history_btn": "📜 History",
        "info_btn": "ℹ️ Information",
        "logout_btn": "🚪 Logout",
        "help_btn": "❓ Help",
        "back_btn": "⬅️ Back",
        "edit_profit_loss_btn": "✏️ Edit Profit/Loss",
        "martin_btn": "Martin",
        "fibo_btn": "Fibo",
        "victory_btn": "Victory",
        "fima_btn": "Fima",
        "stages_calculator_btn": "Stages Calculator",
        "capital1_btn": "Capital1",
        "select_capital1_btn": "Select Capital1",
        "capital2_btn": "Capital2",
        "select_capital2_btn": "Select Capital2",
        "capital3_btn": "Capital3",
        "select_capital3_btn": "Select Capital3",
        "select_btn": "✅ Select",
        "signal_start_msg1": "Start RED-GREEN 1MIN strategy.\nSignal starts after 5 minutes.",
        "signal_start_msg4": "Start Blocks 1MIN strategy.\nSignal starts after 5 minutes.",
        "result_red": "RED   🔴",
        "result_green": "GREEN   🟢",
        "result_big": "BIG   🔷",
        "result_small": "SMALL   🔶",
        "result_odd": "LẺ   🔢",
        "result_even": "CHẴN   🔢",
        "signal_red": "Red",
        "signal_green": "Green",
        "signal_big": "Big",
        "signal_small": "Small",
        "signal_odd": "Odd",
        "signal_even": "Even",
        "result_win": "Win",
        "result_lose": "Lose",
        "result": "Result",
        "buy": "BUY",
        "signal_start_msg5": "Start Dices 1MIN strategy.\nSignal starts after 5 minutes.",
        "signal_start_msg2": "👉 Use the following control characters:\n▫️ B: Big\n▫️ S: Small\n▫️ G: Green\n▫️ R: Red\n▫️ P: Purple\n▫️ O: Odd\n▫️ E: Even\n▫️ 0–9: Used to indicate bet level or amount\n\n✒️ Example:\n\nBx1 (Bet on Big, with bet 1)\n\nGx3 (Bet on Green, with bet 3)",
        "signal_start_msg3": "Ready to receive commands...",
        "trading_active": "🟢 Trading Active",
        "trading_stopped": "🔴 Trading Stopped",
        "group_selected": "📋 Group: {0}",
        "group_not_selected": "📋 Group: Not selected",
        "user_panel_info": "👤 **User:** {username}\n💰 **Balance:** {balance}\n{group}\n🎯 **Status:** {status}\n\nSelect an option:",
        "target_panel_info": "🎯 <b>Target Settings</b>\n\n👤 <b>User:</b> {username}\n💰 <b>Balance:</b> {balance}\n\n🏁 <b>Stop Take Profit:</b> {take_profit}\n🛑 <b>Stop Loss:</b> {stop_loss}\n\n💼 <b>Capital Management:</b> {capital_strategy}",
        "edit_profit_loss_prompt": "Send your take profit and stop loss in this format:\n\ntake profit:100\nstoploss:50",
        "custom_strategy_selected": "✅ Custom strategy {0} selected!",
        "custom_strategy_saved": "✅ Custom capital management plan saved for {custom_key}!\nPlan: {plan}",
        "prompt_base_amount": "Please enter your base trade amount for {strategy} (e.g., 1.0):",
        "prompt_sequence_plan": "Please enter your full sequence for {strategy} (e.g., 1-2-3-4):",
        "prompt_custom_capital_strategy": "Send your custom capital management plan for {custom_key} (e.g., 1-3-8-24):",
        "group_not_found": "Group not found",
        "please_select_group": "❌ Please select a group first!",
        "please_login_to_coinvid": "❌ Please login to Coinvid first!",
        "unknown_action": "Unknown action",
        "error_occurred": "An error occurred: {e}",
        "base_amount_set": "✅ Base amount set for {strategy}: {amount}",
        "invalid_base_amount": "❌ Invalid base amount. Please enter a number.",
        "sequence_set": "✅ Sequence set for {strategy}: {sequence}",
        "username_activated": "✅ Username is activated! Logging in to Coinvid...",
        "coinvid_login_success": "✅ Coinvid login successful! You are now logged in.",
        "info_panel_info": "<b>ℹ️ Information</b>\n\n👤 <b>USERNAME:</b> {username}\n{status} <b>STATUS</b>\n💵 <b>INITIAL BALANCE:</b> {initial_balance}$\n💰 <b>CURRENT BALANCE:</b> {balance}$\n📈 <b>CURRENT PROFIT:</b> {profit}$\n🎯 <b>TAKE PROFIT:</b> {take_profit}$\n🛑 <b>STOP LOSS:</b> {stop_loss}$\n👥 <b>GROUP NAME:</b> {group}\n💼 <b>CAPITAL MANAGEMENT:</b> {capital_mgmt}\n🔢 <b>CAPITAL1:</b> {capital1}\n🔢 <b>CAPITAL2:</b> {capital2}\n🔢 <b>CAPITAL3:</b> {capital3}",
        "capital_management_panel_info": "<b>Capital Management</b>\n\n<b>Selected strategy:</b> {strategy}\n▫️ Base amount: {base_amount}\n▫️ Plan: {custom_plans}\n\n<b>Custom Strategies:</b>\n▫️ Capital1: {capital1}\n▫️ Capital2: {capital2}\n▫️ Capital3: {capital3}",
        "command_received": "💥Buy: {color} {color_emoji}    👉Stage: {phase}",
        "blocks_command_received": "💥Buy: {type} {type_emoji}    👉Stage: {phase}",
        "dices_command_received": "💥Buy: {type} {type_emoji}    👉Stage: {phase}",
        "big": "Big",
        "small": "Small",
        "red": "Red",
        "green": "Green",
        "odd": "Odd",
        "even": "Even",
        "add_group": "➕ Add Group",
        "delete_group": "🗑️ Delete",
        "language_toggle": "🌐 Language",
        "add_group_prompt_title": "📝 **Add New Group**",
        "add_group_prompt_message": "Please send the group ID to add:",
        "add_group_requirements": "⚠️ **Requirements:**\n• The bot must be in the group\n• The bot must be an admin in the group",
        "delete_group_confirm_title": "🗑️ **Delete Group Confirmation**",
        "delete_group_confirm_message": "Are you sure you want to delete the group:\n**{group_name}**\n\n⚠️ This action cannot be undone!",
        "yes_delete": "✅ Yes, Delete",
        "cancel": "❌ Cancel",
        "group_deleted_success": "✅ **Group Deleted Successfully!**",
        "group_deleted_message": "The group **{group_name}** has been permanently deleted.",
        "group_added_success": "✅ **Group Added Successfully!**",
        "group_added_with_info": "**Group:** {chat_title}\n**ID:** {group_id}\n**Username:** @{chat_username}",
        "group_added_fallback": "**Group:** {group_name}\n**ID:** {group_id}\n\n⚠️ **Note:** Could not retrieve group title. Make sure the bot is in the group and is an admin.",
        "invalid_group_id": "❌ **Invalid Group ID**",
        "invalid_group_id_message": "Please send a valid numeric group ID.",
        "error_adding_group": "❌ **Error Adding Group**",
        "bot_not_admin": "The bot is not an administrator in the group.",
        "bot_not_admin_warning": "⚠️ **Warning:** The bot is not an administrator in the group, but the group has been added.",
        "group_added_with_warning": "**Group:** {chat_title}\n**ID:** {group_id}\n**Username:** @{chat_username}\n\n⚠️ **Warning:** Bot is not an admin in this group.",
        "group_info": "**Group:** {chat_title}\n**ID:** {group_id}",
        "language_changed": "✅ Language changed to {lang_emoji} {lang_text}!",
        "edit_description_prompt": "Send the new description for group '{group_name}':",
        "add_username_prompt": "Send username to add new user:",
        "delete_username_prompt": "Send username to delete:",
        "user_not_found": "User not found",
        "invalid_admin_id": "Invalid admin ID",
        "description_updated": "✅ Description updated for '{group_name}'!",
        "new_description": "New description: {new_description}",
        "group_id_text": "Group ID: {group_id}",
        "current_language": "**Current Language:** {lang_emoji} {lang_text}",
        "chat_id_text": "Chat ID: {chat_id}",
        "bot_activated_success": "✅ **Bot Activated Successfully!** ✅\n\n🎉 **Status:** Bot is working properly\n📋 **Chat Type:** {chat_type}\n\n📛 **Chat Name:** {chat_name}",
        "bot_activation_failed": "❌ **Activation Failed!** ❌\n\n⚠️ **Error:** {error}\n\n🔧 **Please ensure:**\n• Bot is added to the group/channel\n• Bot has admin permissions\n• Bot can send messages\n\n📞 **Contact support if the issue persists.**",
        "signal_acknowledgment": "🎯 **SIGNAL ACKNOWLEDGED**\n\n📥 **Signal:** {signal}\n📋 **Group:** {group_name}\n⏰ **Time:** {timestamp}",
        "background_signal_processed": "✅ **Background signal processed successfully!**",
        "command_code_sent": "✅ **Command code sent:** {command_code}",
        "signal_monitoring_active": "🔄 **Signal monitoring active**",
        "old_signal_skipped": "⏭️ **Old signal skipped** (older than 5 minutes)",
        "signal_cleaner_active": "🧹 **Signal cleaner active**"
    },
    "vi": {
        "welcome": "Chào mừng! Vui lòng chọn một tùy chọn:",
        "login": "🔐 Đăng nhập",
        "language": "🌐 Ngôn ngữ",
        "back": "⬅️ Quay lại",
        "english": "🇺🇸 Tiếng Anh",
        "vietnamese": "🇻🇳 Tiếng Việt",
        "login_prompt": "Để kích hoạt tên người dùng của bạn, hãy liên hệ với quản trị viên @admin\nHoặc gửi thông tin của bạn như sau: `tên người dùng&mật khẩu`",
        "contact_admin": "Liên hệ admin: /admin_username",
        "login_success": "✅ Đăng nhập thành công! Chào mừng trở lại.",
        "login_failed": "❌ Thông tin đăng nhập không hợp lệ. Vui lòng thử lại.",
        "session_expired": "⚠️ Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
        "home": "🏠 Trang chủ",
        "groups": "📋 Nhóm",
        "settings": "⚙️ Cài đặt",
        "start": "▶️ Bắt đầu",
        "stop": "⏹️ Dừng",
        "logout": "🚪 Đăng xuất",
        "done": "✅ Xong",
        "select": "✅ Chọn",
        "group_selected": "✅ Đã chọn",
        "group_description": "Mô tả nhóm",
        "admin_panel": "🔧 Bảng quản trị",
        "group_list": "📋 Danh sách nhóm",
        "add_username": "➕ Thêm tên người dùng",
        "delete_username": "➖ Xóa tên người dùng",
        "search_usernames": "🔍 Tìm kiếm tên người dùng",
        "online_list": "🟢 Danh sách trực tuyến",
        "added_list": "📝 Danh sách đã thêm",
        "remove": "🗑️ Xóa",
        "add_admin": "➕ Thêm admin",
        "remove_admin": "➖ Xóa admin",
        "added_admins": "👥 Admin đã thêm",
        "admin_add_prompt": "Gửi ID admin mới để thêm:",
        "admin_remove_prompt": "Gửi ID admin để xóa:",
        "admin_added": "✅ Thêm admin thành công!",
        "admin_removed": "✅ Xóa admin thành công!",
        "user_info": "Thông tin người dùng",
        "username": "Tên người dùng",
        "status": "Trạng thái",
        "online": "🟢 Trực tuyến",
        "offline": "🔴 Ngoại tuyến",
        "no_groups": "Không có nhóm nào",
        "no_users": "Không có người dùng nào",
        "no_admins": "Không có admin nào",
        "group_added": "✅ Thêm nhóm thành công!",
        "group_removed": "✅ Xóa nhóm thành công!",
        "group_updated": "✅ Cập nhật nhóm thành công!",
        "edit": "✏️ Chỉnh sửa",
        "username_added": "✅ Thêm tên người dùng thành công!",
        "username_removed": "✅ Xóa tên người dùng thành công!",
        "invalid_format": "❌ Định dạng không hợp lệ. Vui lòng sử dụng: username&password",
        "already_logged_in": "Bạn đã đăng nhập rồi!",
        "not_logged_in": "Vui lòng đăng nhập trước!",
        "not_admin": "❌ Truy cập bị từ chối. Chỉ dành cho admin.",
        "session_days": "Phiên hợp lệ trong 3 ngày",
        "coinvid_login_failed": "❌ Đăng nhập Coinvid thất bại. Vui lòng kiểm tra thông tin đăng nhập.",
        "trading_started": "✅ Giao dịch đã bắt đầu! Sẵn sàng nhận tín hiệu.",
        "trading_stopped": "🛑 Giao dịch đã dừng!",
        "group_not_selected": "❌ Vui lòng chọn một nhóm trước!",
        "credentials_missing": "❌ Vui lòng đăng nhập Coinvid trước!",
        "signal_received": "🎯 Tín hiệu đã nhận và thực thi!",
        "trade_success": "✅ Giao dịch thực thi thành công!",
        "trade_failed": "❌ Giao dịch thực thi thất bại!",
        "balance_updated": "💰 Số dư đã cập nhật!",
        "cmd_user_only": "❌ Lệnh này chỉ có thể được sử dụng bởi người dùng, không phải là kênh hoặc quản trị viên ẩn danh.",
        "login_btn": "🔐 Đăng nhập",
        "language_btn": "🌐 Ngôn ngữ",
        "groups_btn": "👥 Nhóm",
        "settings_btn": "⚙️ Cài đặt",
        "start_btn": "▶️ Bắt đầu",
        "stop_btn": "⏹️ Dừng",
        "target_btn": "🎯 Mục tiêu",
        "capital_mgmt_btn": "💼 Quản lý vốn",
        "history_btn": "📜 Lịch sử",
        "info_btn": "ℹ️ Thông tin",
        "logout_btn": "🚪 Đăng xuất",
        "help_btn": "❓ Trợ giúp",
        "back_btn": "⬅️ Quay lại",
        "edit_profit_loss_btn": "✏️ Chỉnh sửa lợi nhuận/lỗ",
        "martin_btn": "Martin",
        "fibo_btn": "Fibo",
        "victory_btn": "Thắng lợi",
        "fima_btn": "Fima",
        "stages_calculator_btn": "Bộ tính toán các giai đoạn",
        "capital1_btn": "Vốn1",
        "select_capital1_btn": "Chọn Vốn1",
        "capital2_btn": "Vốn2",
        "select_capital2_btn": "Chọn Vốn2",
        "capital3_btn": "Vốn3",
        "select_capital3_btn": "Chọn Vốn3",
        "select_btn": "✅ Chọn",
        "signal_start_msg1": "Bắt đầu chiến lược RED-GREEN 1MIN.\nTín hiệu bắt đầu sau 5 phút.",
        "signal_start_msg4": "Bắt đầu chiến lược Đoán khối 1MIN.\nTín hiệu bắt đầu sau 5 phút.",
        "result_red": "ĐỎ   🔴",
        "result_green": "XANH   🟢",
        "result_big": "LỚN   🔷",
        "result_small": "NHỎ   🔶",
        "result_odd": "LẺ   🔢",
        "result_even": "CHẴN   🔢",
        "signal_red": "Đỏ",
        "signal_green": "Xanh",
        "signal_big": "Lớn",
        "signal_small": "Nhỏ",
        "signal_odd": "Lẻ",
        "signal_even": "Chẵn",
        "result_win": "Thắng",
        "result_lose": "Thua",
        "result": "Kết quả",
        "buy": "MUA",
        "signal_start_msg5": "Bắt đầu chiến lược Xóc Đĩa 1MIN.\nTín hiệu bắt đầu sau 5 phút.",
        "signal_start_msg2": "👉 Sử dụng các ký tự điều khiển sau:\n▫️ B: Lớn\n▫️ S: Nhỏ\n▫️ G: Xanh\n▫️ R: Đỏ\n▫️ P: Tím\n▫️ O: Lẻ\n▫️ E: Chẵn\n▫️ 0–9: Được sử dụng để chỉ định mức cược hoặc số tiền\n\n✒️ Ví dụ:\n\nBx1 (Đặt cược lớn, với cược 1)\n\nGx3 (Đặt cược xanh, với cược 3)",
        "signal_start_msg3": "Sẵn sàng nhận lệnh...",
        "trading_active": "🟢 Giao dịch đang hoạt động",
        "trading_stopped": "🔴 Giao dịch đã dừng",
        "group_selected": "📋 Nhóm: {0}",
        "group_not_selected": "📋 Nhóm: Chưa chọn",
        "user_panel_info": "👤 **Người dùng:** {username}\n💰 **Số dư:** {balance}\n{group}\n🎯 **Trạng thái:** {status}\n\nChọn một tùy chọn:",
        "target_panel_info": "🎯 <b>Cài đặt mục tiêu</b>\n\n👤 <b>Người dùng:</b> {username}\n💰 <b>Số dư:</b> {balance}\n\n🏁 <b>Dừng lấy lợi nhuận:</b> {take_profit}\n🛑 <b>Dừng lỗ:</b> {stop_loss}\n\n💼 <b>Quản lý vốn:</b> {capital_strategy}",
        "edit_profit_loss_prompt": "Gửi lợi nhuận và dừng lỗ của bạn theo định dạng này:\n\nlợi nhuận:100\nlỗ:50",
        "custom_strategy_selected": "✅ Chiến lược tùy chỉnh {0} đã chọn!",
        "custom_strategy_saved": "✅ Kế hoạch quản lý vốn tùy chỉnh đã lưu cho {custom_key}!\nKế hoạch: {plan}",
        "prompt_base_amount": "Vui lòng nhập số tiền cược cơ bản cho {strategy} (ví dụ: 1.0):",
        "prompt_sequence_plan": "Vui lòng nhập chuỗi đầy đủ cho {strategy} (ví dụ: 1-2-3-4):",
        "prompt_custom_capital_strategy": "Gửi kế hoạch quản lý vốn tùy chỉnh của bạn cho {custom_key} (ví dụ: 1-3-8-24):",
        "group_not_found": "Không tìm thấy nhóm",
        "please_select_group": "❌ Vui lòng chọn một nhóm trước!",
        "please_login_to_coinvid": "❌ Vui lòng đăng nhập Coinvid trước!",
        "unknown_action": "Hành động không xác định",
        "error_occurred": "Đã xảy ra lỗi: {e}",
        "base_amount_set": "✅ Số tiền cơ bản đã đặt cho {strategy}: {amount}",
        "invalid_base_amount": "❌ Số tiền cơ bản không hợp lệ. Vui lòng nhập một số.",
        "sequence_set": "✅ Chuỗi đã đặt cho {strategy}: {sequence}",
        "username_activated": "✅ Tên người dùng đã được kích hoạt! Đăng nhập vào Coinvid...",
        "coinvid_login_success": "✅ Đăng nhập Coinvid thành công! Bạn đã đăng nhập.",
        "info_panel_info": "<b>ℹ️ Thông tin</b>\n\n👤 <b>TÊN NGƯỜI DÙNG:</b> {username}\n{status} <b>TRẠNG THÁI</b>\n💵 <b>SỐ DƯ KHỞI ĐẦU:</b> {initial_balance}$\n💰 <b>SỐ DƯ HIỆN TẠI:</b> {balance}$\n📈 <b>LỢI NHUẬN HIỆN TẠI:</b> {profit}$\n🎯 <b>LỢI NHUẬN:</b> {take_profit}$\n🛑 <b>DỪNG LỖ:</b> {stop_loss}$\n👥 <b>TÊN NHÓM:</b> {group}\n💼 <b>QUẢN LÝ VỐN:</b> {capital_mgmt}\n🔢 <b>VỐN1:</b> {capital1}\n🔢 <b>VỐN2:</b> {capital2}\n🔢 <b>VỐN3:</b> {capital3}",
        "capital_management_panel_info": "<b>Quản lý vốn</b>\n\n<b>Chiến lược đã chọn:</b> {strategy}\n▫️ Số tiền cơ bản: {base_amount}\n▫️ Kế hoạch: {custom_plans}\n\n<b>Chiến lược tùy chỉnh:</b>\n▫️ Vốn1: {capital1}\n▫️ Vốn2: {capital2}\n▫️ Vốn3: {capital3}",
        "command_received": "💥Mua: {color} {color_emoji}    👉Giai đoạn: {phase}",
        "blocks_command_received": "💥Mua: {type} {type_emoji}    👉Giai đoạn: {phase}",
        "dices_command_received": "💥Mua: {type} {type_emoji}    👉Giai đoạn: {phase}",
        "big": "Lớn",
        "small": "Nhỏ",
        "red": "Đỏ",
        "green": "Xanh",
        "odd": "Lẻ",
        "even": "Chẵn",
        "add_group": "➕ Thêm nhóm",
        "delete_group": "🗑️ Xóa",
        "language_toggle": "🌐 Ngôn ngữ",
        "add_group_prompt_title": "📝 **Thêm nhóm mới**",
        "add_group_prompt_message": "Vui lòng gửi ID nhóm để thêm:",
        "add_group_requirements": "⚠️ **Yêu cầu:**\n• Bot phải có trong nhóm\n• Bot phải là quản trị viên trong nhóm",
        "delete_group_confirm_title": "🗑️ **Xác nhận xóa nhóm**",
        "delete_group_confirm_message": "Bạn có chắc chắn muốn xóa nhóm:\n**{group_name}**\n\n⚠️ Hành động này không thể hoàn tác!",
        "yes_delete": "✅ Có, xóa",
        "cancel": "❌ Hủy",
        "group_deleted_success": "✅ **Xóa nhóm thành công!**",
        "group_deleted_message": "Nhóm **{group_name}** đã được xóa vĩnh viễn.",
        "group_added_success": "✅ **Thêm nhóm thành công!**",
        "group_added_with_info": "**Nhóm:** {chat_title}\n**ID:** {group_id}\n**Tên người dùng:** @{chat_username}",
        "group_added_fallback": "**Nhóm:** {group_name}\n**ID:** {group_id}\n\n⚠️ **Lưu ý:** Không thể lấy tên nhóm. Hãy đảm bảo bot có trong nhóm và là quản trị viên.",
        "invalid_group_id": "❌ **ID nhóm không hợp lệ**",
        "invalid_group_id_message": "Vui lòng gửi ID nhóm số hợp lệ.",
        "error_adding_group": "❌ **Lỗi thêm nhóm**",
        "bot_not_admin": "Bot không phải là quản trị viên trong nhóm.",
        "bot_not_admin_warning": "⚠️ **Cảnh báo:** Bot không phải là quản trị viên trong nhóm, nhưng nhóm đã được thêm.",
        "group_added_with_warning": "**Nhóm:** {chat_title}\n**ID:** {group_id}\n**Username:** @{chat_username}\n\n⚠️ **Cảnh báo:** Bot không phải là admin trong nhóm này.",
        "group_info": "**Nhóm:** {chat_title}\n**ID:** {group_id}",
        "language_changed": "✅ Đã thay đổi ngôn ngữ thành {lang_emoji} {lang_text}!",
        "edit_description_prompt": "Gửi mô tả mới cho nhóm '{group_name}':",
        "add_username_prompt": "Gửi tên người dùng để thêm người dùng mới:",
        "delete_username_prompt": "Gửi tên người dùng để xóa:",
        "user_not_found": "Không tìm thấy người dùng",
        "invalid_admin_id": "ID admin không hợp lệ",
        "description_updated": "✅ Đã cập nhật mô tả cho '{group_name}'!",
        "new_description": "Mô tả mới: {new_description}",
        "group_id_text": "ID nhóm: {group_id}",
        "current_language": "**Ngôn ngữ hiện tại:** {lang_emoji} {lang_text}",
        "chat_id_text": "ID chat: {chat_id}",
        "bot_activated_success": "✅ **Bot đã được kích hoạt thành công!** ✅\n\n🎉 **Trạng thái:** Bot đang hoạt động bình thường\n📋 **Loại chat:** {chat_type}\n\n📛 **Tên chat:** {chat_name}",
        "bot_activation_failed": "❌ **Kích hoạt thất bại!** ❌\n\n⚠️ **Lỗi:** {error}\n\n🔧 **Vui lòng đảm bảo:**\n• Bot đã được thêm vào nhóm/kênh\n• Bot có quyền quản trị viên\n• Bot có thể gửi tin nhắn\n\n📞 **Liên hệ hỗ trợ nếu vấn đề vẫn tiếp tục.**",
        "signal_acknowledgment": "🎯 **TÍN HIỆU ĐÃ NHẬN**\n\n📥 **Tín hiệu:** {signal}\n📋 **Nhóm:** {group_name}\n⏰ **Thời gian:** {timestamp}",
        "background_signal_processed": "✅ **Tín hiệu nền đã được xử lý thành công!**",
        "command_code_sent": "✅ **Mã lệnh đã được gửi:** {command_code}",
        "signal_monitoring_active": "🔄 **Giám sát tín hiệu đang hoạt động**",
        "old_signal_skipped": "⏭️ **Tín hiệu cũ đã bỏ qua** (quá 5 phút)",
        "signal_cleaner_active": "🧹 **Dọn dẹp tín hiệu cũ đang hoạt động**"
    }
}

def get_text(key, lang="en"):
    """Get translated text based on language"""
    return LANGUAGES.get(lang, LANGUAGES["en"]).get(key, key) 